#!/bin/zsh

test -e pubspec.yaml || ( echo Run the comand in the root of Flutter project! && kill $$ )
cd proto || ( echo You must store the proto files in the proto directory! && kill $$ )
echo removing old genereated entries
rm -rf ../lib/proto/*
echo generating
protoc -I /Users/vidklopcic/StudioProjects/flutter_persistent_socket/proto  --dart_out=../lib/proto **/*.proto
echo refactoring imports
sed -i '' 's/files.pb.dart/package:flutter_persistent_socket\/proto\/files.pb.dart/g' ../lib/proto/*
echo adding to git
git add ../lib/proto
echo 'done'