#!/usr/bin/python3
import os
import subprocess as s
import sys
import json

if not os.path.isdir('proto') or not os.path.isfile('fps_config.json'):
    print('Run the command from python project root, containing proto directory and fps_config.json!')
    sys.exit(1)
s.run('rm -rf ./proto/*', shell=True)
config = json.load(open('fps_config.json'))
proto_path = ' '.join(['-I ' + i for i in config['protos']])
protos = ' '.join(['/' + i.strip('/') + '**/*.proto' for i in config['protos']])

s.run('protoc -I /Users/vidklopcic/StudioProjects/flutter_persistent_socket/proto %s  --python_betterproto_out=proto /Users/vidklopcic/StudioProjects/flutter_persistent_socket/proto**/*.proto %s' % (proto_path, protos), shell=True)
s.run('fps_python_server_message_gen /Users/vidklopcic/StudioProjects/flutter_persistent_socket/proto**/*.proto %s' % protos, shell=True)
